### PR TITLE
refactor safeguards module

### PR DESCRIPTION
**Pull request by bast**

### CODE REVIEW

**Comment by bast** [comment]
Good point I need to check that. Yes, the versioning needs some more thinking.

**Comment by robertodr** [comment]
Autocmake as a curated repository of utilities sounds doable. Handling everything from 2.8.z to 3.y.z is anyway unrealistic...

**Comment by bast** [comment]
Created #243 to discuss this.

**Comment by bast** [comment]
Indeed fails with 2.8 - thanks for catching this. I will park this PR until we decide how we deal with versions.

**Comment by bast** [comment]
We are now in the future. Merging.

**Pull request merged**
